### ISSUE TITLE
Not able to view the notebook.

### ISSUE THREAD

**Issue by amitjslearn** [knathanieltucker/seaborn-weird-parts#1]
Not able to view the notebook, from this link  which I got from your youtube viedo (https://www.youtube.com/redirect?v=2gUzVX2yfWA&event=video_description&redir_token=jLWibN9XVqn2xTARdeDXXyTsV8d8MTU3MDk1OTg3NEAxNTcwODczNDc0&q=https%3A%2F%2Fgithub.com%2Fknathanieltucker%2Fseaborn-weird-parts%2Fcommit%2F6197f89a63cc1da2babff4e27f7c032421dc6624)

**Comment by knathanieltucker** [comment]
Thanks for the issue! I went ahead and changed the link in the video!
